name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.5", "3.x"]
    name: Python ${{ matrix.python }} sample

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: make install
    - name: Unit tests
      run: make unit
    - name: Install test dependencies
      run: make dev-install
    - name: Lint with flake8
      run: make lint
